spring:
  application:
    # 应用名
    name: sm_rtDesign
  profiles:
    # 选择应用所使用的环境对应参数 dev,fat,sit,uat
    active: default
  #用来程序引导时执行，应用于更加早期配置信息读取，如可以使用来配置application.yml中使用到参数等
  #application.yml 加载，application.yml先于application-active.yml加载，后加载覆盖前加载
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化物理连接个数
      initial-size: 1
      #最小连接池数量
      min-idle: 1
      #最大连接池数量
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #用来检测连接是否有效的sql，要求是一个查询语句,如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
      validation-query: SELECT 'X' FROM DUAL
      #申请连接的时候检测，如果空闲时间大于imeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: true
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      max-pool-prepared-statement-per-connection-size: 20
      #最小空闲连接数保活
      keep-alive: true
      #以下为基于spring boot web的内嵌druid监控，若需开启请将三个值均置为true
      stat-view-servlet:
        enabled: false
      web-stat-filter:
        enabled: false
      filter:
        stat: false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/rtdesign?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  #web端口
  port: 9999
  tomcat:
    uri-encoding: utf-8
logging:
  #logback地址
  config: classpath:logback-spring.xml

mybatis:
  type-aliases-package: com.dcits.entity  # MyBatis注解形式扫描实体类路径
  config-location:  classpath:mybatis-config.xml  # MyBatis XML形式配置文件路径(指定全局配置文件的位置)
  mapper-locations: classpath:mapper/*_Mapper.xml

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  params: count=countSql
  supportMethodsArguments: true


